name: Dart CI

on:
  push:
    branches:
      - fix/*
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Flutter Runner
    - uses: jddeep/Flutter-Runner@1.2.0
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
