name: Daily Mobile Pipeline

on:
  push:
    branches:
      - fix/*
      - feature/*

jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - name: check the repo
      uses: geowatson/flutter-latest@1.0.0

  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # required

      - uses: axel-op/dart-package-analyzer@stable
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check scores
        run: |
          MAINTENANCE_SCORE=${{ steps.analysis.outputs.maintenance }}
          HEALTH_SCORE=${{ steps.analysis.outputs.health }}
          if (( $(echo "$MAINTENANCE_SCORE < 100" | bc) )) || (( $(echo "$HEALTH_SCORE < 100" | bc) ))
          then
            echo "Scores are not both equal to 100"
            exit 1
          fi  
